### ISSUE TITLE
New Onboarding flow

### ISSUE THREAD

**Issue by katiahristova** [sami79031/LoopholeFunctionsTesting#7]
@sami79031 Onboarding works for me now, I tested. Tom says the source of the error was some resource allocation thing. If you see any errors still please make comments below. If not, we can move on with the new flow:

The onboarding flow will now have just one screen.
1. If the user signs up with any of the social logins they should go straight to the Home Screen of the app -- none of the other screens should show up (currently we also see screens asking them to connect streaming accounts, connect with friends, etc).
2. If the user signs up with email this is what their sign up screen should look like and after this screen they also go straight to the Home Screen of the app:

![Image](https://user-images.githubusercontent.com/11900627/266384617-fca684d9-37a5-4afc-80fa-95e1f487e079.png)

Tom says the API is ready to handle not receiving values for the extra parameters. 

As you reroute the onboarding flow please don't delete any of the screens that we no longer show, because they are or will be used in other parts of the app.

**Comment by sami79031** [comment]
There is a problem with the update user API. It returns a success but in reality the first and last name are null after fetching the user's profile.  Only once happened to see that the names were saved successfully. Here is a screenshot of the request and response. I debugged and made sure that we have a valid JWD token. 

For the body I'm passing only firstName & lastName. Everything else is passed as an empty string.

`body: jsonEncode({
              'user_fname': firstName,
              'user_lname': lastName,
              'user_uname': userName,
              'user_phone': phone,
              'user_gender': gender,
              'user_birth': birth,
              'userPhotoURL': photo,
            }))`

![Image](https://github.com/sami79031/LoopholeFunctionsTesting/assets/9218154/af7e18c2-d6b8-43cb-a2f8-ecc4ad8aa4ce)

**Comment by sami79031** [comment]
@katiahristova 
I was able to go around this by using a different screen that used to build user's profile. Essentially just gives some more time for the backend to arrange its internal things.
It seems to be working now. Test it and will create a PR if all is good.
There was one more thing that I fixed. The logic for the user's icon was messed up. It's fixed as well.
You can add another 30min on top of all.

**Comment by katiahristova** [comment]
@sami79031 a couple of questions:
1. How many hours so far for this work? We haven't given any estimate for this, they just wanted it done ASAP.
2. I should still let Tom know about the update user API, right? Even though you found a work around for the onboarding? He should know this and the hours you spent on this debug. 
3. Which API did you end up using that works for the name?

**Comment by sami79031** [comment]
1. 8h
2. No, it's fine
3. The same API. The only difference was which screen to use next. There is a screen named "Build" that essentially gives the app some time to fetch all the user data needed.

**Comment by sami79031** [comment]
@katiahristova 
please test
