### ISSUE TITLE
Profile screen changes due to onboarding flow changes

### ISSUE THREAD

**Issue by katiahristova** [sami79031/LoopholeFunctionsTesting#8]
1. Remove username from under the user's profile picture

2. In Profile and edit profile remove the username field. For the remaining fields please check that if no value is provided they just show up empty. Currently some seem to take on some default value -- for example the birth year defaults to 2023. I don't know if this comes from the backend or it's how the UI is coded? Please let me know if it's the backend so I can tell Tom.

**Comment by katiahristova** [comment]
@sami79031 Here are the username related changes.

**Comment by sami79031** [comment]
@katiahristova 
Done
